### PR TITLE
Add toggle for secure text

### PR DESCRIPTION
**Pull request by colcalex**
Closes [issue #175 ](https://github.com/code4romania/monitorizare-vot-ios/issues/175).

Used [sfssymbols](https://github.com/davedelong/sfsymbols) tool to export **SFSymbols** (iOS13+) to png. The reason is that the icons should be easily recognisable to iOS users, as they are recommended icons for the ecosystem.

Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-30 at 21 53 23
Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-30 at 21 53 19

### CODE REVIEW

**Comment by CristiHabliuc** [comment]
@colcalex Thanks for taking care of this! Please make some changes to this screen to make it look a bit nicer:

- smaller eye icon
- please use `eye.fill` and slashed for better readability
- please set an alpha of 0.4 to make it less intrusive

shot

**Comment by CristiHabliuc** [comment]
+1 for using symbols 👌

**Comment by colcalex** [comment]
Thanks @CristiHabliuc, good pointers for the design. I think this should be closer to the design you've provided. I think there's still a possibility to play around with the different eye configurations, but as far as I can tell this is the clearer to the user. I worry an eye/eye.fill combination could be quite confusing and the slash is definitely useful to inform eye is closed.

Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-06 at 22 19 19
Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-06 at 22 19 15

**Comment by CristiHabliuc** [comment]
Awesome, thanks Alex!

**Pull request merged**
